name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          version: 3.3.4
          name: monstrous
          preset: Monstrous
          projectDir: projects/monstrous
          run: godot --headless
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Monstrous
          path: surfpossum.github.io/projects/monstrous
