name: Build Godot Project

on:
  push:
    paths:
      - 'projects/monstrous/buildTrigger.txt'

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game Job
    steps:
      - name: checkout
        uses: actions/checkout@v4
#      - name: install wine
#        id: wine_install
#        run: |
#          sudo apt install wine64
#          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
      - name: export game
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./projects/monstrous # build the standard project
          relative_export_path: ./projects/monstrous/build # move export output to this directory relative to git root
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Monstrous
          path: /projects/monstrous
