on:
  push

jobs:
  export_game:
    name: Export Game Job
    steps:
      - name: export game
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
          relative_project_path: ./projects/monstrous # build the standard project
          relative_export_path: ./projects/monstrous # move export output to this directory relative to git root
          archive_output: true
